apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-todoapp-deploy
  labels:
    app: local-todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-todoapp
  template:
    metadata:
      labels:
        app: local-todoapp
    spec:
      containers:
      - name: app
        image: local/todoapp:v1
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /data
          name: test-volume
      volumes:
        - name: test-volume
          hostPath:
            # directory location on host
            path: /data
---
apiVersion: v1
kind: Service
metadata:
  name: local-todoapp-svc
spec:
  type: NodePort
  selector:
    app: local-todoapp
  ports:
  - name: local-todoapp-port
    protocol: TCP
    port: 8080
    targetPort: 8080